version: "3.8"

services:
  app:
    image: cr.yandex/crpf4id8lbgetpgvvgss/devops-back
    container_name: app
    environment:
      - YANDEX_USE_CLOUD=TRUE
      - AWS_ACCESS_KEY=
      - AWS_SECRET_KEY=
      - AWS_BUCKET_NAME=
      - DATABASE_CONNECTION=
    ports:
      - 800:80
      - 4430:443
    networks:
      - my-network

  front:
    image: cr.yandex/crpf4id8lbgetpgvvgss/devops-front
    container_name: front
    depends_on:
      - app
    ports:
      - 1337:80
    networks:
      - my-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - my-network


networks:
  my-network:
    driver: bridge